---
title: "ESM 244 Lab 5"
author: "Kiera Matiska"
date: "2/3/2022"
output: html_document
---

```{r setup, include = TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)

# for part 1, PCA:
library(ggfortify)
library(palmerpenguins)
library(patchwork)

# for part 2, ggplot customization
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)
```

# Part 1: PCA (Principle Components Analysis)

```{r}
penguin_clean <- penguins %>% 
  drop_na()

penguin_pca <- penguin_clean %>% 
  select(body_mass_g, ends_with("_mm")) %>% # ends_with is tidyr, keeps certain variable in the original subset
  scale() %>% 
  prcomp()

# Run in console:
# - penguin_pca
# - penguin_pca$rotation (only gives table)
# - penguin_pca$sdev (only gives standard deviations)
```

## Biplot by hand

```{r}
loadings_df <- data.frame(penguin_pca$rotation) %>% 
  mutate(axis = row.names(.))

new_pts_df <- data.frame(penguin_pca$x)

ggplot() +
  geom_point(data = new_pts_df, 
             aes(x = PC1, y = PC2), color = "blue") +
  geom_segment(data = loadings_df,
               x = 0, y = 0,
               aes(xend = PC1, yend = PC2, group = axis),
               arrow = arrow(length = unit(.25, "cm"))) +
  geom_text(data = loadings_df, 
            aes(x = PC1, y = PC2, label = axis),
            vjust = 0, nudge_y = 0.02) + # vjust = verticle justification; nudge_y pushes labels upward a tiny bit
  theme_minimal()
```

```{r}
autoplot(penguin_pca,
         data = penguin_clean, 
         loadings = TRUE,
         colour = "species",
         loadings.label = TRUE,
         loadings.colour = "black",
         loadings.label.colour = "black",
         loadings.label.vjust = -0.5) +
  scale_color_manual(values = c("blue", "purple", "orange")) +
  theme_minimal()
```

## Screeplot by hand

```{r}
sd_vec <- penguin_pca$sdev
var_vec <- sd_vec ^ 2

pc_names <- colnames(penguin_pca$rotation)
pct_expl_df <- data.frame(v = var_vec,
                          pct_v = var_vec / sum(var_vec),
                          pc = fct_inorder(pc_names)) %>% 
  mutate(pct_lbl = paste0(round(pct_v * 100, 1), "%"))

ggplot(pct_expl_df,
       aes(x = pc, y = v)) +
  geom_col() +
  geom_text(aes(label = pct_lbl), vjust = 0, nudge_y = 0.005) +
  labs(x = "Principal Component", y = "Variance Explained")
# If you want a graph to look pretty, this is the way to go
```

```{r}
# harder to customize these
screeplot(penguin_pca, type = "lines")
screeplot(penguin_pca, type = "barplot")
```

# Part 2: ggplot customization, reading in different file types

```{r}
fish_noaa <- read_excel(here("data", "foss_landings.xlsx")) %>% # may also use read_xlsx
  janitor::clean_names() %>% 
  mutate(across(where(is.character), tolower)) %>% 
  mutate(nmfs_name = str_sub(nmfs_name, end = -4)) %>% 
  filter(confidentiality == "public")
```

```{r}
fish_plot <- ggplot(data = fish_noaa,
                    aes(x = year, y = pounds, group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) +
  theme_minimal()

ggplotly(fish_plot) # interactive graph

ggplot(data = fish_noaa,
       aes(x = year, y = pounds, group = nmfs_name)) +
  geom_line() +
  gghighlight(nmfs_name == "rockfishes") + # highlights specific variables so it sticks out
  theme_minimal()

ggplot(data = fish_noaa,
       aes(x = year, y = pounds, group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) +
  gghighlight(max(pounds) > 1e8) + # highlight based on max catch
  theme_minimal()
```

## Read in data from URL and practive some lubridate

```{r}
monroe_wt <- read_csv("https://raw.githubusercontent.com/oharac/esm244_w22_lab5/master/data/MWTP_Elec_Daily.csv") %>% 
  janitor::clean_names()

monroe_ts <- monroe_wt %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  mutate(record_month = lubridate::month(date),
         month_name = month.abb[record_month]) %>% 
  mutate(month_name = fct_reorder(month_name, record_month))

ggplot(data = monroe_ts,
       aes(x = month_name, y = total_kwh)) +
  geom_jitter(aes(color = month_name),
              show.legend = FALSE,
              alpha = 0.5, # makes it transparent
              size = 0.3, # defines the point size
              height = 0, # defines height
              width = 0.2) +
  theme_classic()
```







